### ISSUE TITLE
standalone browser script

### ISSUE THREAD

**Issue by viebel** [prayerslayer/js.spec#13]
Is there a bundled script for js.spec that can run independently in the browser?

**Comment by prayerslayer** [comment]
Not yet, I'm afraid. Until it's there you could:

~~~
npm install js.spec
cp ./node_modules/js.spec/dist/js.spec.js <wherever>
~~~

What would be your preferred way of obtaining such a script?

**Comment by viebel** [comment]
I tried that but it didn't work... I got an error 
```
module is not defined
```
If you could host this file on your repo - it would be great.

**Comment by prayerslayer** [comment]
Ah, of course. Because I compile for nodejs target and it generates `module.exports` 😕

**Comment by viebel** [comment]
I also tried 
`browserify ./node_modules/js.spec/dist/js.spec.js -o spec.js -s spec`

**Comment by prayerslayer** [comment]
Give me 10 minutes :grin:

**Comment by prayerslayer** [comment]
I added a UMD bundle and updated the [readme section](https://github.com/prayerslayer/js.spec#installation). A quick local test worked for me, could you try yourself?

**Comment by viebel** [comment]
It doesn't work for me. See here: https://jsfiddle.net/viebel/j8y0rprs/2/

**Comment by prayerslayer** [comment]
Which browser do you use?

**Comment by prayerslayer** [comment]
And what error do you get? On a relatively new chrome and mobile safari I get the expected alert with "true".

**Comment by viebel** [comment]
I'm on Chrome 54.

The basic problem is that `window['js.spec']` is undefined...

![image](https://cloud.githubusercontent.com/assets/955710/20917075/1626a046-bb98-11e6-8052-22865ef26304.png)

**Comment by prayerslayer** [comment]
Maybe like so? https://jsfiddle.net/j8y0rprs/3/

Problem for me was that Github apparently does not set the MIME type of the file when you load it like you did, and then Chrome refuses to execute.

**Comment by viebel** [comment]
Oh. That works fine now.

What do you say about making your documentation interactive, with [KLIPSE](https://github.com/viebel/klipse)  -  a tool of mine :) ?

I made an html page with `valid` and `conform` interactive examples. Take a look here: http://viebel.github.io/klipse/examples/js.spec.html

It's super simple to use klipse inside a git book. Here are the instructions: https://book.klipse.tech/

**Comment by prayerslayer** [comment]
Interactive docs are neat, will definitely consider it! One thing that I noticed quickly: KLIPSE doesn't print Symbols, which is unfortunate since `conform` will return a special symbol in case the data does not conform to the spec.

![image](https://cloud.githubusercontent.com/assets/878512/20918146/c8c56262-bb95-11e6-9f69-9a8c355b4f9e.png)

I will close this issue since your original request is resolved, if you want to continue to discuss things we can do that elsewhere (e.g. other issue if applicable). Thank you very much for suggestion and interest! :party:

**Comment by viebel** [comment]
I have the same problem with displayin infinity.

The reason is that i am stringifying the result with json.parse in order to
embed the result in the div that displays the result.

But infinity and symbol are not part of json.

Do you have an idea how to solve this issue?

**Comment by viebel** [comment]
I am in the middle of a PR that solves this issue https://github.com/viebel/klipse/pull/149

**Comment by prayerslayer** [comment]
> Do you have an idea how to solve this issue?

I'd use something like this: https://github.com/thejameskyle/pretty-format

**Comment by viebel** [comment]
Thanks a lot. I have included it in klipse.
Could you make sure that now, the symbols are displayed properly?

**Comment by viebel** [comment]
@prayerslayer are the symbols displayed properly now?

Are you interested by an interactive doc for `js.spec` with KLIPSE?
