### ISSUE TITLE
Registry aliases?

### ISSUE THREAD

**Issue by mattbishop** [prayerslayer/js.spec#19]
I'm working on a PR for js.spec and am short some unit testing coverage. Istanbul showed me a branch in registry.get() that is not tested:

```
export function get(id) {
  const s = REGISTRY[id]
  if (typeof s !== 'symbol') {
    return s
  }
  return get(s)  // <-- here is the untested branch
}
```

My interpretation of this code is that one could define an alias symbol for another Spec's symbol, and then use either symbol to fetch the defined spec. I have a test that looks like this:

```
    it("defines an alias to another defined spec and gets the aliased spec back", () => {
      const id = Symbol()
      const spec = {}
      define(id, spec)
      const alias = Symbol("alias")
      define(alias, id)
      const actual = get(alias)
      expect(actual).to.equal(spec)
    })
```

This test fails with:
```
TypeError: Cannot create property 'name' on symbol 'Symbol()'
    at define (lib/registry.js:19:3)
    at Context.<anonymous> (test/registry.test.js:20:7)
```

The problem is the second `define(alias, id)` call; define() assumes that spec is not a symbol and sets the name property.

Am I misinterpreting the purpose of Symbol values in Registry? How would I even define such a thing?

**Comment by prayerslayer** [comment]
Damnit, I knew this `spec.name` would bite me. The line in `registry.get` is actually unrelated to the registry; the registry does/should not care about a spec's name, it only needs an ID to look up.

What you describe is correct, `get` should allow for aliases. The use of symbols itself is a recommendation to have guaranteed unique IDs and make accidentally overwriting a spec of another module very hard.

Two possible solutions:

* check in `define` if we define an alias and don't set name then
* allow to set name explicitly by user, fall back to default name like in current `toString` implementations

I'd rather have the second, what do you think?

**Comment by mattbishop** [comment]
I am not sure what the value of 'name' is; it doesn't exist in clojure.spec. Symbol is close enough to clojure keyword to be the main naming concept the users will need. The fantastic thing about Symbol is that it provides a clear way to find a named spec anywhere in the app in a manner similar to a clojure keyword: `registry.get(Symbol.for("beach/blanket"))`.

It seems the main value of name is in `explain` output. In that case I would be interested in the registry symbol being explicitly called out; storing it in name is ambiguous. Did I set the name when I constructed the spec or did it get set when I defined it in the registry?

**Comment by mattbishop** [comment]
Another problem with `define()` is that it overwrites any existing name value on the spec.

Name value aside, my proposed fix to define() is this:
```
  if (!spec.name && typeof spec !== "symbol") {
    spec.name = getName(id)
  }
```
This preserves existing behaviour (autonaming spec from symbol) without throwing errors trying to set symbol.name. It doesn't make sense to name a symbol anyways. It also fixes the issue where the name is not overwritten.

**Comment by prayerslayer** [comment]
> I am not sure what the value of 'name' is; it doesn't exist in clojure.spec

Useful `explain` output, as you guessed, is pretty much the only reason why it's there. In Clojure I could just print the symbol (as in "variable name") itself, but not in JS.

> In that case I would be interested in the registry symbol being explicitly called out; storing it in name is ambiguous.

Naming is hard :grin:

> Did I set the name when I constructed the spec or did it get set when I defined it in the registry?

The latter. But I could imagine allowing to provide a name when the spec is constructed, then setting in `define()` when it's not there.

> Another problem with define() is that it overwrites any existing name value on the **spec.**

I don't think it's too much a problem, since it's not part of a specs public API.

**Comment by prayerslayer** [comment]
Closing due to #21
