### ISSUE TITLE
Registry

### ISSUE THREAD

**Issue by prayerslayer** [prayerslayer/js.spec#21]
In #19 and #20 some confusion arose around the purpose of the registry. Currently it has the following responsibilities, which may or may not be useful:

#### Store available specs for easier access

So you can do this:

~~~ javascript
define("string", p.string)
conform("string", "foo")
~~~

Instead of always having to do it like this:

~~~ javascript
const string = p.string
conform(string, "foo")
~~~

However the underlying question is probably how different modules share their specs or provide them to "userspace." Should they `define` all their things to store them in the registry? (I don't think it's possible with `npm` as, if I recall correctly, you can end up with depdendency A using js.spec v1 and dependency B with js.spec v1.1, effectively using different registry instances) Also, they still would need to share they IDs to look up in the registry.

~~~ javascript
// module A
export const specA = Symbol("string")
define(specA, p.string)

// module B
import {specA} from 'a'
conform(specA, "foo")
~~~

So maybe overall it's better to use regular es6 modules for transporting specs directly.

~~~ javascript
// module A
export const specA = p.string

// module B
import {specA} from 'a'
conform(specA, "foo")
~~~

Which would make the registry obsolete.

#### Name the specs

The one other reason why the registry exists is that, since you give a semantically useful ID to `define`, it can auto-name the specs, which is super important for error messages. Generic error messages are not helpful, especially when you consider two syntactically equal specs that have different semantics. (It's in the morning, I don't have a good example ready.)

Here I would just make the `name` part of a spec's data, it's cleaner anyways.

**Comment by mattbishop** [comment]
Using modules makes more sense in a JS context. It simplifies the design and also improves the understandability--I can directly inspect the imported spec, whereas in a registry it's hard to see where it came from, or worse, who redefined it.

**Comment by mattbishop** [comment]
I would also argue for an exported `spec.predicate(myFn, name)` that would return a properly-named spec for a given user-defined function.

**Comment by scotttrinh** [comment]
I might be missing something here, but aren't all specs functions and don't functions already have a `.name` property?

**Comment by mattbishop** [comment]
Yes it has a name property, but it's supposed to be read-only: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function/name

**Comment by prayerslayer** [comment]
> I might be missing something here, but aren't all specs functions and don't functions already have a .name property?

Specs are objects, see for instance [`map`](https://github.com/prayerslayer/js.spec/blob/master/lib/spec/map.js#L7). Predicates are always functions (but also specs and thus objects, haha), but since any function can be a predicate, you can provide an anonymous function (it's also more comfortable), and that doesn't have a name.

Also, regarding naming, even if specs would be functions, they would by default just be named `Map`, for instance, which doesn't help you debugging at all if you have a couple of map specs that are also nested.

**Comment by prayerslayer** [comment]
So to sum it up, we agreed on:

* Removing the registry
* Thus no longer allowing specs to be referenced by symbol or string ID
* Making the name part of the spec/predicate API

**Comment by mattbishop** [comment]
Sounds right to me.

**Comment by prayerslayer** [comment]
Closing as `1.0.0-2` incorporates the discussed changes, feel free to continue the discussion if necessary.

**Comment by laczoka** [comment]
Maybe I am beating a dead horse already, but the spec registry also enables an important feature:
if a spec for a namespaced key exists, it's value can be checked against it's spec. 
Namespaced key semantics are defined independently of their object/map, which avoids repeated definition of keys with identical semantics in different map/object contexts.

See [1] and [2].

[1] https://clojure.org/about/spec#_map_specs_should_be_of_keysets_only
[2] https://clojure.org/about/spec#_decomplect_maps_keys_values

**Comment by DjebbZ** [comment]
As I'm currently using (and loving!) Clojure(Script) and its `spec` lib, I agree strongly with @laczoka. You don't want to repeat specs for different maps. You want to model your business with semantically correct names and reuse the associated specs as much as possible across modules (namespace in clj parlance) and projects.

Not sure the current design without the registry helps with this.

**Comment by mattbishop** [comment]
JS doesn't have a socially-acceptable concept of global state. One gets the illusion of shared state via `require` but it breaks down as soon as one module embeds js.spec. The registry stops being shared at that point. You could put a registry up in the global object but that's bad form in JS.

A more JS-appreciative approach is to export your specs in a module and then `require` that module into those places that need that spec. This is not the same as clojurescript, for sure, but when in Rome...

**Comment by DjebbZ** [comment]
Indeed, I understand how it could easily break.

Keep up the good work !
