### ISSUE TITLE
spec.map not working as described

### ISSUE THREAD

**Issue by carocad** [prayerslayer/js.spec#22]
running the example from the documentation

```
const person = spec.map("person", {
  email: spec.string
  })

// Error: Cannot use Map spec with shape person
```

I couldnt find anything in the code that would be causing that but after checking [this line](https://github.com/prayerslayer/js.spec/blob/6f2851dc7ea8b09e8f0727a95dfd55baaf18daf5/lib/spec/map.js#L65) I figured that somehow the name was being passed as the shape object.

and voila!
```
spec.map({email: spec.string, [spec.optional]: {}}, "foo")
t {
  options:
   { requiredKeys: [ 'email', 'undefined' ],
     requiredSpecs: { email: [Function: p], undefined: {} },
     optionalKeys: [],
     optionalSpecs: {} },
  name: '' }
```

sadly, I dont know why or where is the name being swapped with the shape.

For the record I am using:
```
js.spec: ^1.0.0-1
node: v6.9.4
```

**Comment by prayerslayer** [comment]
Yeah sorry, that changed as of version 1.0.0-2, which I didn't tag as latest yet. Will fix when I'm home.

**Comment by prayerslayer** [comment]
![image](https://cloud.githubusercontent.com/assets/878512/24722711/11560708-1a45-11e7-9be6-462e0d77e9d5.png)

`npm install js.spec` will now install `1.0.0-2`.
