### ISSUE TITLE
allow spec.map to work with an empty map

### ISSUE THREAD

**Issue by thought2** [prayerslayer/js.spec#25]
`spec.map("sth", {})`

throws the error `Cannot use Keys spec without keys.`

Well, it's the same as `spec.object`

But it would be nice to do something like this:
`spec.map("sth", {[optional]: {a: spec.string}})`

So I think there should just be no checking for empty maps, it's ok when they are empty.

**Comment by prayerslayer** [comment]
Yup, good idea. clojure.spec also doesn't do this afaik.

**Comment by thought2** [comment]
nice, by the way, I'm just hacking on some 'generate' function for
js.spec. Would you maybe welcome a pull request regarding this?

Generally I thought it might be a good approach to just have a generate
method in the `Spec` class. For instance the one for the Collection
subclass could look like:

`
  generate() {
    const defLen = 20;
    const min = this.options[minCount] || 0;
    const max = this.options[maxCount] || defLen;
    const n = this.options[count] || _.random(min, max);
    const xs = _.times(n, () => this.options.spec.generate());
    return _.sample([true, false]) ? xs : (new Set (xs))
  }

`

Now I'm figuring out, how this could be done for builtin and custom
predicates.

What would be a nice interface for people to write their custom generators?

`myPredicate = (x) => (x == 2)`

And then, in case the `predicate` function would be exported to the user...:

`

p = predicate('', myPredicate)

p.generator = () => _.sample([true, false])

myspec = spec.collection('', p)

`

And then the `specize` would have to be enhanced to pattern match on the
built in predicates in order to attach the right generator for them,
which might be inside a 'generators.js' module or so.

Another option would be to have the exports (spec.string, spec.bool) to
be of type `Predicate` already, but I don't know if this would break too
much.

If you have some comments regarding this, I'd be curious to hear...

Michael

**Comment by prayerslayer** [comment]
Hi, sorry for the late response. I didn't put any thoughts into generation _at all_ yet, so I'm happy to have something to discuss. My original plan was to generate checkers for [`testcheck-js`](https://github.com/leebyron/testcheck-js) from the available spec metadata, like required keys for a map. Then users could leverage that to write the actual assertions. But I'm not sure how much can be actually abstracted away, especially due to the lack of reflection in JS (I can define a predicate `x => x > 10`, but from the outside I have no idea what it's doing).

**Comment by mattbishop** [comment]
This is the same issue as https://github.com/prayerslayer/js.spec/issues/40

@arichiardi found that clojure is OK with optional-only map specs: https://github.com/prayerslayer/js.spec/issues/40#issuecomment-321199533

**Comment by prayerslayer** [comment]
Should be fixed with #41 thanks to @mattbishop
