### ISSUE TITLE
Improve explainStr message

### ISSUE THREAD

**Issue by arichiardi** [prayerslayer/js.spec#26]
Hello @prayerslayer! First of all thanks for the port!

I am playing with it from TypeScript and have the following spec:

```
/**
 * Return true if there are no spaces
 */
export function hasNoSpaces(s: string): boolean {
  const regex = new RegExp(/\s+/);
  return !regex.test(s);
}

export const AggregateSegmentSpec = S.spec.and("s_aggregateSegment", S.spec.string, hasNoSpaces);

```

When it fails the message is:

`"s_aggregateSegment → hasNoSpaces: hasNoSpaces failed for undefined at []."`

Which is a bit cryptic and probably has a bug in it (see `undefined`).

I'll try to have a look but can't promise anything :smile:

**Comment by prayerslayer** [comment]
Haha, yeah. One of this library's goals was to unify error messages, but I couldn't focus on that part yet (as we first need to _find_ the errors). Would definitely appreciate improvements and suggestions!

**Comment by arichiardi** [comment]
So what I see if I dump `problems` in `explainData` is:

```
[ { path: [],
    via: [ 'DataPathSpec', 'p' ],
    value: ... ]
```

and the `getIn(value, problem.path)` of course always returns `undefined`.
Maybe `spec.and` does not build the correct `path` for the specs.
Debugging time is over for now, just wanted to write down this little discovery.

**Comment by prayerslayer** [comment]
So the working idea of `path` was that it includes the path in a nested structure to access the failing value. If there is no nested structure involved, it's always empty. I'm not sure what to do, should it in your example contain the index of the offending character?

**Comment by arichiardi** [comment]
@prayerslayer I see now. My predicate is arbitrary so what I think `clojure.spec` is doing is just to show the value that fails. It we had a way for a predicate to specify a failing "path" we would be actually better than `clojure.spec` at this :smile:

**Comment by prayerslayer** [comment]
Alright, so I think all there is to do is to exclude `path` from the explanation when it's empty. I'd like it to point to a character in a string, but think it's not easily doable with native JS regexes. We would need a regex engine like regex101.com has, where we can access intermediate steps.

**Comment by arichiardi** [comment]
Yeah removing that would solve thing and make it less confusing I guess. Good solution for now!

**Comment by mattbishop** [comment]
Is this now fixed?

**Comment by arichiardi** [comment]
I think so, the message got improved. The regex specific message can be handled in another issue I guess. Thanks a lot for the fix!
