### ISSUE TITLE
False positive or feature?

### ISSUE THREAD

**Issue by arichiardi** [prayerslayer/js.spec#28]
Hello @prayerslayer,

I was playing again with `js.spec` but I think I am either getting things wrong or found a problem.

I have the following spec:

```
export const DD = S.spec.map("DD", {
  name: S.string,
});

export const AD = S.spec.map("AD", {
  name: S.string,
  domain: DD
});

export const AI = S.spec.map("AI", {
  id: S.string,
  definition: AD
});
```

When I try `S.assert(spec.AI, aggId)` where `aggId` is:

```
{
  "id": "-",
  "definition": {
    "domain": {
      "name": "my-domain-name"
    },
    "name": "order and prices"
  }
}
```

I get:

```
Error: AI → AD → Keys(AD): predicate failed for order and prices at [definition, name].
AI → AD → Keys(AD): predicate failed for undefined at [definition, undefined].
AI → AD → Keys(AD): predicate failed for [object Object] at [definition, domain].
```

Am I doing something wrong?

**Comment by mattbishop** [comment]
Did you try without 'export' ? That puts the value in the 'exports' object.

**Comment by arichiardi** [comment]
Uhm no, I don't see why that would that make a difference, but at the end of the day I am a JS newbie 😀

**Comment by prayerslayer** [comment]
This works for me (changed `example.js`, running with `babel-node`):

~~~ javascript
import { spec, valid, explain, conform, assert } from './index'
export const DD = spec.map("DD", {
  name: spec.string,
});

export const AD = spec.map("AD", {
  name: spec.string,
  domain: DD
});

export const AI = spec.map("AI", {
  id: spec.string,
  definition: AD
});


assert(AI, {
  "id": "-",
  "definition": {
    "domain": {
      "name": "my-domain-name"
    },
    "name": "order and prices"
  }
})
~~~

So I think there's something else going on, if you provide the missing pieces of your code I might be able to help out.

**Comment by prayerslayer** [comment]
So apparently the issue was what happened in #30 (undefined predicates in map), closing this now.
