### ISSUE TITLE
Add some sugar for chai testing

### ISSUE THREAD

**Issue by arichiardi** [prayerslayer/js.spec#29]
Hello folks!

I had this idea for quite a bit and I was wondering what you think about it.

Reading [here](https://github.com/chaijs/chai/issues/81#issuecomment-6654108) I can see that we could basically add chai assertions around the spec validation, something like:

```
chai.use(function (_chai, _) {
  _chai.Assertion.addMethod('conform', function (msg) {
    _.flag(this, 'message', msg);
  });
});

expect(a).to.conform(spec);
```

Some inspiration is here: https://github.com/chaijs/chai-json-schema/blob/master/index.js#L125

It can be a separate module maybe, what do you think?

**Comment by prayerslayer** [comment]
Yes, this definitely crossed my mind also. Would be cool if we could plug js.spec anywhere, eg. also [`prop-types`](https://www.npmjs.com/package/prop-types) and what not. Could be a separate module where all the bindings to other libraries are, but I don't think js.spec is there yet :/

**Comment by arichiardi** [comment]
I got something working yesterday in TypeScript. I started a project. Simple conform only for now 😁

**Comment by arichiardi** [comment]
@prayerslayer the lib is [js-spec-chai](https://github.com/arichiardi/js-spec-chai) and apparently it works only against `master` for some reason.

I could not figure out why I get a strange `Cannot coerce whatever to spec` unless I am linking master.

**Comment by arichiardi** [comment]
I also added one test, which oddly enough is not failing (but it should).
https://github.com/arichiardi/js-spec-chai/blob/master/test/index.test.ts#L68

Maybe you can have a look and if it is a bug I will open an issue for it.

**Comment by prayerslayer** [comment]
The problem is probably how you use the predicates. They're exported in the `spec` key. Consider:

~~~ javascript
import * as s from 'js-spec'
console.log(s.string)
// => undefined
console.log(s.spec.string)
// => Function
~~~

So you're building up your maps with `undefined` predicates and so is the behavior, I'm afraid 😅  This is something js.spec could warn about though.

**Comment by arichiardi** [comment]
Oh right I always make this mistake 😀
-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by prayerslayer** [comment]
Soo given that you started a separate library, is there anything left to do or can I close this? What would be your desired outcome of this issue?

**Comment by arichiardi** [comment]
Yep, closing putting the link in here for the last time.

[js-spec-chai](https://github.com/arichiardi/js-spec-chai/)

**Comment by arichiardi** [comment]
@prayerslayer sorry if I write in a closed issue, but can I ask you to release master at some point? As I was describing here, `1.0.0-3` does not work with `js-spec-chai` at the moment.

**Comment by prayerslayer** [comment]
There is nothing to release, `1.0.0-3` has the current master if I didn't mess things up. Could you elaborate how and what exactly doesn't work?

**Comment by arichiardi** [comment]
Oh ok, so one thing is that there is no tag...but the problem is another one.

For some reason, unless I use `yarn link js.spec` with commit `672ef7b`  and a brand new `yarn run build`, I get `Cannot coerce the-name-of-my-spec-object to spec`.

**Comment by arichiardi** [comment]
I will try to expand more on why this happens, but I was wondering if there has been some building issue in there, I am going to try `1.0.0-2` as well.

**Comment by arichiardi** [comment]
You know, never mind, I removed `node_modules` and life is good, sorry for the noise!
