### ISSUE TITLE
Warn about undefined predicates

### ISSUE THREAD

**Issue by arichiardi** [prayerslayer/js.spec#30]
Logging here what happened in https://github.com/arichiardi/js-spec-chai.
When mistakely using predicates that resolve in `undefined`, warn the user.

For instance this should be detected and avoided:

```
import * as s from 'js-spec'
console.log(s.string)
// => undefined
console.log(s.spec.string)
// => Function
```

Peace :peace_symbol:

**Comment by prayerslayer** [comment]
In `1.0.0-10` you should see an error whenever you try to use undefined predicates :)

**Comment by arichiardi** [comment]
Awesome thank you!
-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.
