### ISSUE TITLE
Assertions with promises

### ISSUE THREAD

**Issue by arichiardi** [prayerslayer/js.spec#32]
Hello @prayerslayer!
I am opening this PR in order to see how you feel about adding wrappers around `assert` (and potentially others) that return a `Promise`.

I know I could do it on my side (and I am :smile:), and it would be as simple as:

```
/**
 * Fullfill or reject the Promise against the spec.
 */
export function assertAsPromise (spec, value) {
  return new Promise((f, r) => {
    S.assert(spec, data);
    f(data);
  });
};
```

but I was wondering whether its place should be here (in `util.js` maybe).

Let me know what you think and I can contribute this back!

**Comment by prayerslayer** [comment]
Can you elaborate what your use case is for this behavior? From my point of view it looks like this kind of Promise support should be done in other libraries, like your chai bindings.

However something like this I could imagine in js.spec, but I have to think about this more:

~~~ javascript
function getUsers() {
  return fetch('/users').then(r => r.json());
}

const usersSpec = spec.oneOrMany("users", spec.map("user", {"name": spec.string})) // not implemented yet!

assert(usersSpec, getUsers())
~~~

**Comment by arichiardi** [comment]
Yeah I guess we need both cases. My use case is to validate before a function that returns a promise, so for instance:

```
async function appendEventToJsonFile(envelope: EventEnvelope): Promise<void> {
  const validEnvelope = await specs.assertAsPromise<EventEnvelope>(specs.EventEnvelope, envelope);
  return appendEventAsync(validEnvelope);
};
```

**Comment by prayerslayer** [comment]
Hm that's the same thing, no? You pass it a promise and it does the assertion.

In principle I'd rather advise users to use await/async for a sync API to their promises. If I'm not mistaken your example can be rewritten as:

~~~ typescript
async function appendEventToJsonFile(envelope: EventEnvelope): Promise<void> {
  const _envelope = await envelope;
  const validEnvelope = specs.assert<EventEnvelope>(specs.EventEnvelope,  _envelope);
  return appendEventAsync(validEnvelope);
};
~~~

Supporting promises at this stage will lead me into all kinds of trouble I don't want to deal with.

**Comment by arichiardi** [comment]
:+1:
