### ISSUE TITLE
Publishing and dist

### ISSUE THREAD

**Issue by arichiardi** [prayerslayer/js.spec#38]
Hello @prayerslayer,

I was publishing a new version of `js.spec` with `np` and it seems like the `dist/js.spec.js` file is included in `.gitignore` now and therefore is not published. This is one of the reasons why I don't see the changes when I import in `node`, I guess node uses `dist/js.spec.js` which is never updated, but I might of course be wrong.

Before changing things I decided to open an issue and ask, so that I don't break things unexpectedly.

Which tool do you use for publishing and is there a reason behind excluding `dist/js.spec.js`?

Thanks as usual!

**Comment by prayerslayer** [comment]
Hi there!

> I was publishing a new version of js.spec with np and it seems like the dist/js.spec.js file is included in .gitignore now and therefore is not published.

That's right. It's the [CommonJS version](https://github.com/prayerslayer/js.spec/blob/master/webpack.config.js#L30) of the library. We don't need it in git because it's generated by `npm` during [install](https://docs.npmjs.com/cli/build). So it is always up to date.

The browser-version is `js.spec.bundle.js`, which we have in git so people can grab it directly and include with a `script` tag if they want.

Does this answer your questions?

**Comment by arichiardi** [comment]
Uhm well when I do the install in my client node code, I don't see the ugliefied version (and errors) that is why I am asking. Maybe I am missing something.

If I `npm link` a local version that one has the ugliefied and working.

That is why yesterday I redeployed but that part of course is ignored. Let me check what is the content of `.npmignore`..

**Comment by arichiardi** [comment]
It is funny everything seems good but when importing npm does not build the ugliefied version then.

**Comment by prayerslayer** [comment]
Interesting. I don't really have time now, but you could try if changing the script name to `install` helps.

https://stackoverflow.com/a/38011927

**Comment by arichiardi** [comment]
Ok no problem for the time, just wanted to double check with you :smile: I can try a couple of things.

**Comment by arichiardi** [comment]
Ok I tried a couple of `next` versions and now I am ready to release a good one. Should I bump to `1.0.1`? What do you think, how do you like to handle versioning?

**Comment by prayerslayer** [comment]
Hey, since I'm still in the phase of figuring things out (as this issue shows) I'd prefer to only bump prerelease versions.

**Comment by arichiardi** [comment]
Ok, sensitive :wink:

**Comment by arichiardi** [comment]
Closing this, thanks for answering!

**Comment by arichiardi** [comment]
@prayerslayer sorry to write here, but I have noticed that `1.0.0-10` did not have a valid `dist` (mangled symbols, including that ones excluded in `webpack` recently). I publish a `1.0.0-11` that solves. I publish using `np` because otherwise I would forget to `yarn build` :smile: I found it is working pretty reliably :+1:
