### ISSUE TITLE
Please review Typescript definitions for js.spec

### ISSUE THREAD

**Issue by mattbishop** [prayerslayer/js.spec#44]
I am preparing a PR for DefinitelyTyped to add a TypeScript definition for js.spec. I plan on maintaining this definition over time.

Before I submit a PR I would appreciate a review: https://github.com/mattbishop/DefinitelyTyped/tree/add-js-spec/types/js.spec

Alternately the type definition file can be part of this project too.

**Comment by arichiardi** [comment]
I thought `Spec` always had options, the rest looks very good.

**Comment by mattbishop** [comment]
Ah you're right.

**Comment by mattbishop** [comment]
This has been merged into DefinitelyTyped. Thanks!
