### ISSUE TITLE
Data generation based on the defined spec.

### ISSUE THREAD

**Issue by pragyanatvade** [prayerslayer/js.spec#73]
I am planning to use js.spec for one of my projects. Is there a way to generate data based on the defined spec?

**Comment by arichiardi** [comment]
There is no data generation in the library at the moment.

**Comment by pragyanatvade** [comment]
Any ideas how can it be implemented? I would like take it up and add that functionality.

**Comment by arichiardi** [comment]
Well you would have to implement data generators.
I don't know to be honest if there is something already out there but I would look for JSON schema generators if anything.

That probably would give you a better idea on how to proceed.

Another thing would be to check how ClojureScript does it if you are familiar with the language. I can send a couple of links over...

**Comment by pragyanatvade** [comment]
I am in the process of learning ClojureScript and Clojure. Sure please send me the corresponding links it will be a great help. Thanks.
